# Generated Constant Definitions
# Based on constant_types.json taxonomy

# =========================================================
# Numerical ID Definitions
# =========================================================

# Risk Scale IDs
RISK_IGNORE = 200
RISK_LOW = 201
RISK_MEDIUM = 202
RISK_ELEVATED = 203
RISK_HIGH = 204
RISK_CRITICAL = 205

# Policy Map IDs
POLICY_ALLOW = 300
POLICY_WARN = 301
POLICY_REDACT = 302
POLICY_BLOCK = 303

# Token Type IDs
TOKEN_JWT = 500
TOKEN_BEARER = 501
TOKEN_BASIC = 502
TOKEN_SESSION_KEY = 503

# Category IDs
CTG_PLATFORM_CREDENTIAL = 1
CTG_CLOUD_CREDENTIAL = 2
CTG_CLOUD_STORAGE = 3
CTG_SAAS_CREDENTIAL = 4
CTG_WEBHOOK_URL = 5
CTG_SERVER_CREDENTIAL = 6
CTG_SERVER_URL = 7
CTG_BACKEND_IP = 8
CTG_MINIAPP_INTERNAL = 9
CTG_MINIAPP_API = 10
CTG_CRYPTO_CONFIG = 11
CTG_DATA_ENCODING = 12
CTG_PII = 13
CTG_PAYMENT = 14
CTG_IDENTIFIER = 15
CTG_OTHERS = 99

# Item Slug IDs

# PLATFORM_CREDENTIAL items (Starting index: 1100)
PLATFORM_APP_SECRET = 1101
PLATFORM_SESSION_KEY = 1102
PLATFORM_ACCESS_TOKEN = 1103

# CLOUD_CREDENTIAL items (Starting index: 1200)
CLOUD_CRED_AK_SK_PAIR = 1201
CLOUD_CRED_UPLOAD_POLICY_SIGNED = 1202
CLOUD_CRED_PASSWORD = 1203
CLOUD_CRED_BASIC_AUTH = 1204
CLOUD_CRED_TOKEN = 1205
CLOUD_CRED_COOKIE = 1206
CLOUD_CRED_NOISE = 1207

# CLOUD_STORAGE items (Starting index: 1300)
CLOUD_BUCKET_NAME = 1301
CLOUD_REGION = 1302
CLOUD_STORAGE_PATH = 1303
CLOUD_UPLOAD_CONFIG = 1304
CLOUD_NOISE = 1305

# SAAS_CREDENTIAL items (Starting index: 1400)
SAAS_MAP_KEY = 1401
SAAS_ANALYTICS_KEY = 1402

# WEBHOOK_URL items (Starting index: 1500)
WEBHOOK_URL = 1501

# SERVER_CREDENTIAL items (Starting index: 1600)
SERVER_CRED_PASSWORD = 1601
SERVER_CRED_TOKEN = 1602
SERVER_CRED_SESSION_KEY = 1603
SERVER_CRED_COOKIE = 1604
SERVER_CRED_NOISE = 1605

# SERVER_URL items (Starting index: 1700)
SERVER_URL_WITH_CREDENTIALS = 1701
SERVER_URL_AUTH = 1702
SERVER_URL_PAYMENT = 1703
SERVER_URL_INTERNAL = 1704
SERVER_URL_API_PLAIN = 1705
SERVER_URL_STATIC = 1706
SERVER_URL_NOISE = 1707

# BACKEND_IP items (Starting index: 1800)
BACKEND_IP_PUBLIC = 1801
BACKEND_IP_PRIVATE = 1802
BACKEND_IP_NOISE = 1803

# MINIAPP_INTERNAL items (Starting index: 1900)
MINIAPP_PAGE_PATH_SENSITIVE = 1901
MINIAPP_PAGE_PATH = 1902
MINIAPP_PLUGIN_URL = 1903
MINIAPP_SCENE_PARAM = 1904
MINIAPP_PATH_ASSET = 1905
MINIAPP_PATH_MODULE = 1906
MINIAPP_NOISE = 1907

# MINIAPP_API items (Starting index: 2000)
MINIAPP_API_PARAMS = 2001

# CRYPTO_CONFIG items (Starting index: 2100)
CRYPTO_ALGORITHM_NAME = 2101
CRYPTO_PRIVATE_KEY = 2102
CRYPTO_PUBLIC_KEY = 2103
CRYPTO_STATIC_IV = 2104
CRYPTO_WEAK_ALGORITHM = 2105
CRYPTO_NOISE = 2106

# DATA_ENCODING items (Starting index: 2200)
ENCODING_BASE64 = 2201
ENCODING_URL = 2202
ENCODING_OTHERS = 2203

# PII items (Starting index: 2300)
PII_SFZID_NAME = 2301
PII_PHONE_NAME = 2302
PII_EMAIL_NAME = 2303
PII_NOISE = 2304

# PAYMENT items (Starting index: 2400)
PAYMENT_REQUEST_PARAMS = 2401
PAYMENT_NONCE = 2402
PAYMENT_PACKAGE = 2403
PAYMENT_SIGN_TYPE = 2404
PAYMENT_PAY_SIGN = 2405
PAYMENT_SECRET = 2406
PAYMENT_NOISE = 2407

# IDENTIFIER items (Starting index: 2500)
ID_DEVICE_IDENTIFIER = 2501
ID_AD_IDENTIFIER = 2502
ID_USER_IDENTIFIER = 2503
ID_ORDER_IDENTIFIER = 2504
ID_NOISE = 2505

# OTHERS items (Starting index: 9900)
OTHER = 9901


# =========================================================
# SLUG_TO_DB Mapping Table
# Maps slug_id -> (kind_id, risk_level)
# Used by scanner_engine.py for database conversion
# =========================================================
SLUG_TO_DB = {
    # CTG_PLATFORM_CREDENTIAL
    PLATFORM_APP_SECRET: (CTG_PLATFORM_CREDENTIAL, RISK_CRITICAL),
    PLATFORM_SESSION_KEY: (CTG_PLATFORM_CREDENTIAL, RISK_CRITICAL),
    PLATFORM_ACCESS_TOKEN: (CTG_PLATFORM_CREDENTIAL, RISK_CRITICAL),
    # CTG_CLOUD_CREDENTIAL
    CLOUD_CRED_AK_SK_PAIR: (CTG_CLOUD_CREDENTIAL, RISK_CRITICAL),
    CLOUD_CRED_UPLOAD_POLICY_SIGNED: (CTG_CLOUD_CREDENTIAL, RISK_HIGH),
    CLOUD_CRED_PASSWORD: (CTG_CLOUD_CREDENTIAL, RISK_CRITICAL),
    CLOUD_CRED_BASIC_AUTH: (CTG_CLOUD_CREDENTIAL, RISK_CRITICAL),
    CLOUD_CRED_TOKEN: (CTG_CLOUD_CREDENTIAL, RISK_CRITICAL),
    CLOUD_CRED_COOKIE: (CTG_CLOUD_CREDENTIAL, RISK_HIGH),
    CLOUD_CRED_NOISE: (CTG_CLOUD_CREDENTIAL, RISK_IGNORE),
    # CTG_CLOUD_STORAGE
    CLOUD_BUCKET_NAME: (CTG_CLOUD_STORAGE, RISK_MEDIUM),
    CLOUD_REGION: (CTG_CLOUD_STORAGE, RISK_LOW),
    CLOUD_STORAGE_PATH: (CTG_CLOUD_STORAGE, RISK_MEDIUM),
    CLOUD_UPLOAD_CONFIG: (CTG_CLOUD_STORAGE, RISK_ELEVATED),
    CLOUD_NOISE: (CTG_CLOUD_STORAGE, RISK_IGNORE),
    # CTG_SAAS_CREDENTIAL
    SAAS_MAP_KEY: (CTG_SAAS_CREDENTIAL, RISK_MEDIUM),
    SAAS_ANALYTICS_KEY: (CTG_SAAS_CREDENTIAL, RISK_LOW),
    # CTG_WEBHOOK_URL
    WEBHOOK_URL: (CTG_WEBHOOK_URL, RISK_CRITICAL),
    # CTG_SERVER_CREDENTIAL
    SERVER_CRED_PASSWORD: (CTG_SERVER_CREDENTIAL, RISK_CRITICAL),
    SERVER_CRED_TOKEN: (CTG_SERVER_CREDENTIAL, RISK_CRITICAL),
    SERVER_CRED_SESSION_KEY: (CTG_SERVER_CREDENTIAL, RISK_CRITICAL),
    SERVER_CRED_COOKIE: (CTG_SERVER_CREDENTIAL, RISK_CRITICAL),
    SERVER_CRED_NOISE: (CTG_SERVER_CREDENTIAL, RISK_IGNORE),
    # CTG_SERVER_URL
    SERVER_URL_WITH_CREDENTIALS: (CTG_SERVER_URL, RISK_CRITICAL),
    SERVER_URL_AUTH: (CTG_SERVER_URL, RISK_HIGH),
    SERVER_URL_PAYMENT: (CTG_SERVER_URL, RISK_HIGH),
    SERVER_URL_INTERNAL: (CTG_SERVER_URL, RISK_ELEVATED),
    SERVER_URL_API_PLAIN: (CTG_SERVER_URL, RISK_LOW),
    SERVER_URL_STATIC: (CTG_SERVER_URL, RISK_LOW),
    SERVER_URL_NOISE: (CTG_SERVER_URL, RISK_IGNORE),
    # CTG_BACKEND_IP
    BACKEND_IP_PUBLIC: (CTG_BACKEND_IP, RISK_ELEVATED),
    BACKEND_IP_PRIVATE: (CTG_BACKEND_IP, RISK_MEDIUM),
    BACKEND_IP_NOISE: (CTG_BACKEND_IP, RISK_IGNORE),
    # CTG_MINIAPP_INTERNAL
    MINIAPP_PAGE_PATH_SENSITIVE: (CTG_MINIAPP_INTERNAL, RISK_ELEVATED),
    MINIAPP_PAGE_PATH: (CTG_MINIAPP_INTERNAL, RISK_LOW),
    MINIAPP_PLUGIN_URL: (CTG_MINIAPP_INTERNAL, RISK_MEDIUM),
    MINIAPP_SCENE_PARAM: (CTG_MINIAPP_INTERNAL, RISK_MEDIUM),
    MINIAPP_PATH_ASSET: (CTG_MINIAPP_INTERNAL, RISK_LOW),
    MINIAPP_PATH_MODULE: (CTG_MINIAPP_INTERNAL, RISK_LOW),
    MINIAPP_NOISE: (CTG_MINIAPP_INTERNAL, RISK_IGNORE),
    # CTG_MINIAPP_API
    MINIAPP_API_PARAMS: (CTG_MINIAPP_API, RISK_LOW),
    # CTG_CRYPTO_CONFIG
    CRYPTO_ALGORITHM_NAME: (CTG_CRYPTO_CONFIG, RISK_LOW),
    CRYPTO_PRIVATE_KEY: (CTG_CRYPTO_CONFIG, RISK_CRITICAL),
    CRYPTO_PUBLIC_KEY: (CTG_CRYPTO_CONFIG, RISK_MEDIUM),
    CRYPTO_STATIC_IV: (CTG_CRYPTO_CONFIG, RISK_MEDIUM),
    CRYPTO_WEAK_ALGORITHM: (CTG_CRYPTO_CONFIG, RISK_ELEVATED),
    CRYPTO_NOISE: (CTG_CRYPTO_CONFIG, RISK_IGNORE),
    # CTG_DATA_ENCODING
    ENCODING_BASE64: (CTG_DATA_ENCODING, RISK_IGNORE),
    ENCODING_URL: (CTG_DATA_ENCODING, RISK_IGNORE),
    ENCODING_OTHERS: (CTG_DATA_ENCODING, RISK_IGNORE),
    # CTG_PII
    PII_SFZID_NAME: (CTG_PII, RISK_CRITICAL),
    PII_PHONE_NAME: (CTG_PII, RISK_HIGH),
    PII_EMAIL_NAME: (CTG_PII, RISK_ELEVATED),
    PII_NOISE: (CTG_PII, RISK_IGNORE),
    # CTG_PAYMENT
    PAYMENT_REQUEST_PARAMS: (CTG_PAYMENT, RISK_ELEVATED),
    PAYMENT_NONCE: (CTG_PAYMENT, RISK_ELEVATED),
    PAYMENT_PACKAGE: (CTG_PAYMENT, RISK_ELEVATED),
    PAYMENT_SIGN_TYPE: (CTG_PAYMENT, RISK_LOW),
    PAYMENT_PAY_SIGN: (CTG_PAYMENT, RISK_HIGH),
    PAYMENT_SECRET: (CTG_PAYMENT, RISK_CRITICAL),
    PAYMENT_NOISE: (CTG_PAYMENT, RISK_IGNORE),
    # CTG_IDENTIFIER
    ID_DEVICE_IDENTIFIER: (CTG_IDENTIFIER, RISK_ELEVATED),
    ID_AD_IDENTIFIER: (CTG_IDENTIFIER, RISK_ELEVATED),
    ID_USER_IDENTIFIER: (CTG_IDENTIFIER, RISK_ELEVATED),
    ID_ORDER_IDENTIFIER: (CTG_IDENTIFIER, RISK_MEDIUM),
    ID_NOISE: (CTG_IDENTIFIER, RISK_IGNORE),
    # CTG_OTHERS
    OTHER: (CTG_OTHERS, RISK_IGNORE),
}
